–û–±–æ–∑–Ω–∞—á–µ–Ω–∏—è:

üìù - –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ, –∫–æ—Ç–æ—Ä–æ–µ –Ω—É–∂–Ω–æ –∑–∞–ø–æ–º–Ω–∏—Ç—å

`# ‚è©`- –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π, —á—Ç–æ —ç—Ç—É —è—á–µ–π–∫—É / —Ñ—É–Ω–∫—Ü–∏—é –Ω—É–∂–Ω–æ –ø—Ä–æ—Å—Ç–æ –∑–∞–ø—É—Å—Ç–∏—Ç—å, –æ–Ω–∞ —É–∂–µ –Ω–∞–ø–∏—Å–∞–Ω–∞

`# ‚úèÔ∏è` - –∫–æ–¥ –≤ —ç—Ç–æ–π —è—á–µ–π–∫–µ / —Ñ—É–Ω–∫—Ü–∏–∏ –º—ã –±—É–¥–µ–º –¥–æ–ø–æ–ª–Ω—è—Ç—å –≤ –ø—Ä–æ—Ü–µ—Å—Å–µ —É—Ä–æ–∫–∞

üë®üèª‚Äçüíª - –∑–∞–¥–∞—á–∞ –¥–ª—è —Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ–≥–æ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è

# –ß–µ–º –º—ã –±—É–¥–µ–º –∑–∞–Ω–∏–º–∞—Ç—å—Å—è –Ω–∞ —É—Ä–æ–∫–µ?

–ú—ã –±—É–¥–µ–º –∏–∑—É—á–∞—Ç—å —è–∑—ã–∫ SQL –∏ —Ä–∞–∑–±–∏—Ä–∞—Ç—å—Å—è —Å —É—Å—Ç—Ä–æ–π—Å—Ç–≤–æ–º –±–∞–∑ –¥–∞–Ω–Ω—ã—Ö.

[–ß–∏—Å—Ç–∞—è —Ä–∞–±–æ—á–∞—è —Ç–µ—Ç—Ä–∞–¥—å –¥–ª—è –∑–∞–ø–æ–ª–Ω–µ–Ω–∏—è](https://colab.research.google.com/drive/1zAd_rqcIHC0UqRAPquRUDKQSgm14-E5X?usp=sharing)

[–ó–∞–ø–æ–ª–Ω–µ–Ω–Ω–∞—è —Ä–∞–±–æ—á–∞—è —Ç–µ—Ç—Ä–∞–¥—å](https://colab.research.google.com/drive/1sRd9sfxir1tdq719VfpGcI8Y0me4v4VG?usp=sharing)

[–ü—Ä–µ–∑–µ–Ω—Ç–∞—Ü–∏—è –∫ —É—Ä–æ–∫—É](https://docs.google.com/presentation/d/1X6S0h1mDZLcYC0f5A7mOpjKqgut9EwAE2TcsTdz2dos/edit?usp=sharing)

In [1]:
!pip install wget

Requirement already satisfied: wget in c:\users\toxidxd\vscprojects\sb_data_science_intensive\.venv\lib\site-packages (3.2)

In [2]:
from wget import download

download('https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite')

'Chinook_Sqlite (1).sqlite'

–ú—ã –±—É–¥–µ–º –ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –±–∞–∑–æ–π –¥–∞–Ω–Ω—ã—Ö [Chinook](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite)

<table>
    <tr><td><img src='https://drive.google.com/uc?export=view&id=1h48Kym2Gy84_3RKrtVhsqbsJMNOqF1gq' width='600' border='0' alt=''></td></tr>
    <tr><td>–ò–∑–æ–±—Ä–∞–∂–µ–Ω–∏–µ —Å <a href="https://ru.pinterest.com/pin/349029039886060219/">Pinterest</a></td></tr>
</table>

In [3]:
import sqlite3

connect = sqlite3.connect("Chinook_Sqlite.sqlite")

In [4]:
import pandas as pd

# SQL

üìù **SQL** (Structured query language) - —è–∑—ã–∫ –∑–∞–ø—Ä–æ—Å–æ–≤ –∫ –±–∞–∑–∞–º –¥–∞–Ω–Ω—ã—Ö

* –ó–∞–ø—Ä–æ—Å—ã –∏–º–µ—é—Ç –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—É—é —Å—Ç—Ä—É–∫—Ç—É—Ä—É
* –ó–∞–ø—Ä–æ—Å—ã –º–æ–≥—É—Ç –±—ã—Ç—å —Ä–∞–∑–±–∏—Ç—ã –Ω–∞ –Ω–µ—Å–∫–æ–ª—å–∫–æ —Å—Ç—Ä–æ—á–µ–∫
* –ù–µ—Å–∫–æ–ª—å–∫–æ –∑–∞–ø—Ä–æ—Å–æ–≤ —Ä–∞–∑–¥–µ–ª—è—é—Ç—Å—è —Ç–æ—á–∫–æ–π —Å –∑–∞–ø—è—Ç–æ–π
* –í –æ—Ç–ª–∏—á–∏–µ –æ—Ç Python, –≤ SQL –±–æ–ª—å—à–∏–µ –∏ –º–∞–ª–µ–Ω—å–∫–∏–µ –±—É–∫–≤—ã - —ç—Ç–æ –æ–¥–Ω–æ –∏ —Ç–æ –∂–µ: –∑–∞–ø–∏—Å–∏ `SELECT` –∏ `select` —ç–∫–≤–∏–≤–∞–ª–µ–Ω—Ç–Ω—ã
* –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ –≤ SQL –Ω–∞—á–∏–Ω–∞—é—Ç—Å—è —Å –¥–≤–æ–π–Ω–æ–≥–æ –¥–µ—Ñ–∏—Å–∞ –∏ –ø—Ä–æ–¥–æ–ª–∂–∞—é—Ç—Å—è –¥–æ –∫–æ–Ω—Ü–∞ —Å—Ç—Ä–æ–∫–∏

# SELECT

–í—ã–±–æ—Ä –¥–∞–Ω–Ω—ã—Ö –∏–∑ —Ç–∞–±–ª–∏—Ü—ã


```sql
SELECT –Ω–∞–∑–≤–∞–Ω–∏—è –∫–æ–ª–æ–Ω–æ–∫ —á–µ—Ä–µ–∑ –∑–∞–ø—è—Ç—É—é
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
```

–ß—Ç–æ–±—ã –≤—ã–±—Ä–∞—Ç—å –≤—Å–µ –∫–æ–ª–æ–Ω–∫–∏, –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è `SELECT *`:

```sql
SELECT *
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
```

In [5]:
# ‚ñ∂Ô∏è‚ñ∂Ô∏è
# –°–æ–∑–¥–∞–¥–∏–º –ø–µ—Ä–µ–º–µ–Ω–Ω—É—é —Å –∑–∞–ø—Ä–æ—Å–æ–º
# –ú–Ω–æ–≥–æ—Å—Ç—Ä–æ—á–Ω—ã–µ –∑–∞–ø—Ä–æ—Å—ã –º–æ–∂–Ω–æ –æ–≥—Ä–∞–Ω–∏—á–∏–≤–∞—Ç—å —Ç—Ä–æ–π–Ω—ã–º–∏ –∫–∞–≤—ã—á–∫–∞–º–∏: ''' ... '''

query = '''
-- –ë–µ—Ä–µ–º –≤—Å–µ —ç–ª–µ–º–µ–Ω—Ç—ã –∏–∑ —Ç–∞–±–ª–∏—Ü—ã Artist
SELECT *
FROM Artist
'''

# –î–∞–Ω–Ω—ã–µ —Å—á–∏—Ç—ã–≤–∞–µ–º —Å—Ä–∞–∑—É –≤ DataFrame
artists = pd.read_sql(query, connect)

In [6]:
artists

     ArtistId                                               Name
0           1                                              AC/DC
1           2                                             Accept
2           3                                          Aerosmith
3           4                                  Alanis Morissette
4           5                                    Alice In Chains
..        ...                                                ...
270       271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
271       272                             Emerson String Quartet
272       273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
273       274                                      Nash Ensemble
274       275                              Philip Glass Ensemble

[275 rows x 2 columns]

In [7]:
# ‚úèÔ∏è
# –ü–æ—Å–º–æ—Ç—Ä–∏–º –∞–Ω–∞–ª–æ–≥–∏—á–Ω–æ –Ω–∞ —Ç–∞–±–ª–∏—Ü—ã Album –∏ Track

albums = pd.read_sql('SELECT * FROM Album', connect)

In [8]:
# ‚úèÔ∏è
tracks = pd.read_sql('SELECT * FROM Track', connect)

In [9]:
albums

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [10]:
tracks

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [11]:
# üë®üèª‚Äçüíª –í—ã–≤–µ–¥–∏—Ç–µ —Ç–∞–±–ª–∏—Ü—ã Customer –∏ Employee
customers = pd.read_sql('SELECT * FROM Customer', connect)

In [12]:
employee = pd.read_sql('SELECT * FROM Employee', connect)

In [13]:
customers

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Lu√≠s,Gon√ßalves,Embraer - Empresa Brasileira de Aeron√°utica S.A.,"Av. Brigadeiro Faria Lima, 2170",S√£o Jos√© dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,K√∂hler,None,Theodor-Heuss-Stra√üe 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,Fran√ßois,Tremblay,None,1498 rue B√©langer,Montr√©al,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bj√∏rn,Hansen,None,Ullev√•lsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,Franti≈°ek,Wichterlov√°,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Hol√Ω,None,Rilsk√° 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
6,7,Astrid,Gruber,None,"Rotenturmstra√üe 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,None,Gr√©trystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
8,9,Kara,Nielsen,None,S√∏nder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falc√£o Filho, 155",S√£o Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",S√£o Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Pra√ßa Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Bras√≠lia,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
33,34,Jo√£o,Fernandes,None,Rua da Assun√ß√£o 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,None,"Rua dos Campe√µes Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
35,36,Hannah,Schneider,None,Tauentzienstra√üe 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,None,Berger Stra√üe 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
37,38,Niklas,Schr√∂der,None,Barbarossastra√üe 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
43,44,Terhi,H√§m√§l√§inen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kov√°cs,None,Erzs√©bet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
48,49,Stanis≈Çaw,W√≥jcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanis≈Çaw.w√≥jcik@wp.pl,4
49,50,Enrique,Mu√±oz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Guti√©rrez,None,307 Macacha G√ºemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

In [14]:
employee

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

# WHERE

–£—Å–ª–æ–≤–∏—è –¥–ª—è —Ñ–∏–ª—å—Ç—Ä–∞—Ü–∏–∏

```sql
SELECT –Ω–∞–±–æ—Ä –∫–æ–ª–æ–Ω–æ–∫ —á–µ—Ä–µ–∑ –∑–∞–ø—è—Ç—É—é –∏–ª–∏ *
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
WHERE —É—Å–ª–æ–≤–∏–µ
```

–ü—Ä–∏–º–µ—Ä —É—Å–ª–æ–≤–∏—è: "–∑–Ω–∞—á–µ–Ω–∏–µ –≤ –∫–æ–ª–æ–Ω–∫–µ —Ä–∞–≤–Ω–æ –∫–∞–∫–æ–º—É-—Ç–æ –∑–Ω–∞—á–µ–Ω–∏—é" - `colname = X`

–ï—â–µ –æ—Ç–ª–∏—á–∏—è –æ—Ç Python:
* –≤ Python —Ä–∞–≤–µ–Ω—Å—Ç–≤–æ –ø—Ä–æ–≤–µ—Ä—è–µ—Ç—Å—è —á–µ—Ä–µ–∑ "==", –∞ –≤ SQL —á–µ—Ä–µ–∑ "="
* –≤ Python —Ç–µ–∫—Å—Ç –æ–±—Ä–∞–º–ª—è–µ—Ç—Å—è –∏ –æ–¥–∏–Ω–∞—Ä–Ω—ã–º–∏, –∏ –¥–≤–æ–π–Ω—ã–º–∏ –∫–∞–≤—ã—á–∫–∞–º–∏, –≤ SQL - —Ç–æ–ª—å–∫–æ –æ–¥–∏–Ω–∞—Ä–Ω—ã–º–∏ (–¥–≤–æ–π–Ω—ã–µ - –¥–ª—è –Ω–∞–∑—ã–≤–∞–Ω–∏–π –∫–æ–ª–æ–Ω–æ–∫)

In [15]:
#  ‚ñ∂Ô∏è‚ñ∂Ô∏è
# –ü—Ä–∏–º–µ—Ä: –≤—ã–≤–µ–¥–µ–º –Ω–∞–∑–≤–∞–Ω–∏—è –≤—Å–µ—Ö —Ç–∞–±–ª–∏—Ü, –∫–æ—Ç–æ—Ä—ã–µ –µ—Å—Ç—å –≤ –±–∞–∑–µ –¥–∞–Ω–Ω—ã—Ö
query = '''
SELECT
    name
FROM
    sqlite_schema
WHERE
    type ='table'
'''

pd.read_sql(query, connect)

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

In [18]:
# üë®üèª‚Äçüíª –í—ã–≤–µ–¥–∏—Ç–µ –∏–∑ —Ç–∞–±–ª–∏—Ü—ã Track –≤—Å–µ –∫–æ–º–ø–æ–∑–∏—Ü–∏–∏,
#   –¥–ª—è –∫–æ—Ç–æ—Ä—ã—Ö Composer = "Wolfgang Amadeus Mozart"
query = """
SELECT * FROM Track WHERE Composer = 'Wolfgang Amadeus Mozart'
"""
pd.read_sql(query, connect)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,3412,"""Eine Kleine Nachtmusik"" Serenade In G, K. 525...",281,2,24,Wolfgang Amadeus Mozart,348971,5760129,0.99
1,3413,"Concerto for Clarinet in A Major, K. 622: II. ...",282,2,24,Wolfgang Amadeus Mozart,394482,6474980,0.99
2,3451,"Die Zauberfl√∂te, K.620: ""Der H√∂lle Rache Kocht...",317,2,25,Wolfgang Amadeus Mozart,174813,2861468,0.99
3,3454,"Symphony No. 41 in C Major, K. 551, ""Jupiter"":...",320,2,24,Wolfgang Amadeus Mozart,362933,6173269,0.99
4,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99

# DISTINCT, MAX, MIN, AVG

–í—ã–≤–æ–¥ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π / –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è –≤ –∫–æ–ª–æ–Ω–∫–µ / –º–∏–Ω–∏–º–∞–ª—å–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è –≤ –∫–æ–ª–æ–Ω–∫–µ / —Å—Ä–µ–¥–Ω–µ–≥–æ


```sql
SELECT distinct(–∏–º—è –∫–æ–ª–æ–Ω–∫–∏)
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
```

```sql
SELECT MAX(–∏–º—è –∫–æ–ª–æ–Ω–∫–∏)
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
```

```sql
SELECT MIN(–∏–º—è –∫–æ–ª–æ–Ω–∫–∏)
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
```

```sql
SELECT MIN(–∏–º—è –∫–æ–ª–æ–Ω–∫–∏), MAX(–∏–º—è –∫–æ–ª–æ–Ω–∫–∏),  AVG(–∏–º—è –∫–æ–ª–æ–Ω–∫–∏)
FROM –Ω–∞–∑–≤–∞–Ω–∏–µ —Ç–∞–±–ª–∏—Ü—ã
```

In [19]:
#  ‚ñ∂Ô∏è‚ñ∂Ô∏è
pd.read_sql('SELECT AVG(Bytes) from Track', connect)

     AVG(Bytes)
0  3.351021e+07

In [20]:
# ‚úèÔ∏è
# –ü–æ—Å–º–æ—Ç—Ä–∏–º, –∫–∞–∫–∏–µ –µ—Å—Ç—å –∂–∞–Ω—Ä—ã (—Ç–∞–±–ª–∏—Ü–∞ Genre, –∫–æ–ª–æ–Ω–∫–∞ name)
pd.read_sql('SELECT distinct(name) from Genre', connect)

                  Name
0                 Rock
1                 Jazz
2                Metal
3   Alternative & Punk
4        Rock And Roll
5                Blues
6                Latin
7               Reggae
8                  Pop
9           Soundtrack
10          Bossa Nova
11      Easy Listening
12         Heavy Metal
13            R&B/Soul
14   Electronica/Dance
15               World
16         Hip Hop/Rap
17     Science Fiction
18            TV Shows
19    Sci Fi & Fantasy
20               Drama
21              Comedy
22         Alternative
23           Classical
24               Opera

In [21]:
# ‚úèÔ∏è
# –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ –º–æ–∂–µ–º –¥–æ–±–∞–≤–∏—Ç—å —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫—É —Å –ø–æ–º–æ—â—å—é ORDER BY name
pd.read_sql('SELECT distinct(name) FROM Genre ORDER BY name', connect)

                  Name
0          Alternative
1   Alternative & Punk
2                Blues
3           Bossa Nova
4            Classical
5               Comedy
6                Drama
7       Easy Listening
8    Electronica/Dance
9          Heavy Metal
10         Hip Hop/Rap
11                Jazz
12               Latin
13               Metal
14               Opera
15                 Pop
16            R&B/Soul
17              Reggae
18                Rock
19       Rock And Roll
20    Sci Fi & Fantasy
21     Science Fiction
22          Soundtrack
23            TV Shows
24               World

In [22]:
# üë®üèª‚Äçüíª –í—ã–≤–µ–¥–∏—Ç–µ —É–Ω–∏–∫–∞–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –¥–ª—è —Ü–µ–Ω—ã —Ç—Ä–µ–∫–∞ UnitPrice —Ç–∞–±–ª–∏—Ü—ã Track.
# –ö–∞–∫–æ–π —Ü–µ–Ω–æ–≤–æ–π —Ä–∞–∑–±—Ä–æ—Å?
pd.read_sql('SELECT distinct(UnitPrice) FROM Track ORDER BY name', connect)

   UnitPrice
0       1.99
1       0.99

In [23]:
# üë®üèª‚Äçüíª –í—ã–≤–µ–¥–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∏ –º–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏—è –¥–ª—è Bytes —Ç–∞–±–ª–∏—Ü—ã Track
pd.read_sql('SELECT MIN(Bytes) FROM Track', connect)

   MIN(Bytes)
0       38747

In [24]:
pd.read_sql('SELECT MAX(Bytes) FROM Track', connect)

   MAX(Bytes)
0  1059546140

# JOIN

–û–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ —Ç–∞–±–ª–∏—Ü. –í —Ç–µ–∫—É—â–µ–π —Å—Ç—Ä—É–∫—Ç—É—Ä–µ —Ç–∞–±–ª–∏—Ü—ã —Å—Å—ã–ª–∫—ä–∞—é—Ç—Å—è –¥—Ä—É–≥ –Ω–∞ –¥—Ä—É–≥–∞ —Å –ø–æ–º–æ—â—å—é –∫–æ–ª–æ–Ω–æ–∫ —Å –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–∞–º–∏, —É–∫–∞–∑—ã–≤–∞—é—â–∏–º–∏ –Ω–∞ –Ω–æ–º–µ—Ä —Å—Ç—Ä–æ–∫–∏ –≤ –¥—Ä—É–≥–æ–π —Ç–∞–±–ª–∏—Ü–µ

**Track**

| TrackId | Name | AlbumId |
|---|---|---|
| 2| Balls to the Wall|2|
|3| Fast As a Shark|3|

**Album**

| AlbumId | Title | ArtistId |
|---|---|---|
| 2| Balls to the Wall|2|
|3| Restless and Wild|2|

**Artist**

| ArtistId | Name |
|---|---|
| 2| Accept|



```sql
SELECT –Ω–∞–∑–≤–∞–Ω–∏—è –∫–æ–ª–æ–Ω–æ–∫
FROM —Ç–∞–±–ª–∏—Ü–∞1
JOIN —Ç–∞–±–ª–∏—Ü–∞2
ON —Ç–∞–±–ª–∏—Ü–∞1.–∫–æ–ª–æ–Ω–∫–∞_id2 = —Ç–∞–±–ª–∏—Ü–∞2.–∫–æ–ª–æ–Ω–∫–∞_id2
```

```sql
SELECT –Ω–∞–∑–≤–∞–Ω–∏—è –∫–æ–ª–æ–Ω–æ–∫
FROM —Ç–∞–±–ª–∏—Ü–∞1
JOIN —Ç–∞–±–ª–∏—Ü–∞2
JOIN —Ç–∞–±–ª–∏—Ü–∞3
JOIN —Ç–∞–±–ª–∏—Ü–∞4
ON —Ç–∞–±–ª–∏—Ü–∞1.–∫–æ–ª–æ–Ω–∫–∞_id2 = —Ç–∞–±–ª–∏—Ü–∞2.–∫–æ–ª–æ–Ω–∫–∞_id2
AND —Ç–∞–±–ª–∏—Ü–∞2.–∫–æ–ª–æ–Ω–∫–∞_id3 = —Ç–∞–±–ª–∏—Ü–∞3.–∫–æ–ª–æ–Ω–∫–∞_id3
AND —Ç–∞–±–ª–∏—Ü–∞3.–∫–æ–ª–æ–Ω–∫–∞_id4 = —Ç–∞–±–ª–∏—Ü–∞4.–∫–æ–ª–æ–Ω–∫–∞_id4
```

In [28]:
# ‚ñ∂Ô∏è‚ñ∂Ô∏è

# –û–±—ä–µ–¥–∏–Ω–∏–º –≤ –æ–¥–Ω—É —Ç–∞–±–ª–∏—Ü—É –¥–∞–Ω–Ω—ã–µ –æ —Ç—Ä–µ–∫–∞—Ö –∏ –∞–ª—å–±–æ–º–∞—Ö

query = '''
SELECT *
FROM Track
JOIN Album
ON Track.AlbumId = Album.AlbumId
'''
pd.read_sql(query, connect)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice,AlbumId,Title,ArtistId
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99,1,For Those About To Rock We Salute You,1
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99,2,Balls to the Wall,2
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99,3,Restless and Wild,2
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99,3,Restless and Wild,2
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99,3,Restless and Wild,2
...,...,...,...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99,343,Respighi:Pines of Rome,226
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99,344,Schubert: The Late String Quartets & String Qu...,272
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99,345,Monteverdi: L'Orfeo,273
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99,346,Mozart: Chamber Music,274
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,275

In [31]:
# ‚ñ∂Ô∏è‚ñ∂Ô∏è

# –û–±—ä–µ–¥–∏–Ω–∏–º –≤ –æ–¥–Ω—É —Ç–∞–±–ª–∏—Ü—É –¥–∞–Ω–Ω—ã–µ –æ–± –∞–ª—å–±–æ–º–∞—Ö –∏ –∞—Ä—Ç–∏—Å—Ç–∞—Ö

query = '''
SELECT *
FROM Artist
JOIN Album
ON Artist.ArtistId = Album.ArtistId
'''
pd.read_sql(query, connect)

,ArtistId,Name,AlbumId,Title,ArtistId
0,1,AC/DC,1,For Those About To Rock We Salute You,1
1,2,Accept,2,Balls to the Wall,2
2,2,Accept,3,Restless and Wild,2
3,1,AC/DC,4,Let There Be Rock,1
4,3,Aerosmith,5,Big Ones,3
...,...,...,...,...,...
342,226,Eugene Ormandy,343,Respighi:Pines of Rome,226
343,272,Emerson String Quartet,344,Schubert: The Late String Quartets & String Qu...,272
344,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",345,Monteverdi: L'Orfeo,273
345,274,Nash Ensemble,346,Mozart: Chamber Music,274
346,275,Philip Glass Ensemble,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,275

In [32]:
# üë®üèª‚Äçüíª –û–±—ä–µ–¥–∏–Ω–∏—Ç–µ –≤—Å–µ 3 —Ç–∞–±–ª–∏—Ü—ã –≤ –æ–¥–Ω—É, —á—Ç–æ–±—ã –º–æ–∂–Ω–æ –±—ã–ª–æ –ø—Ä–æ—Å–ª–µ–¥–∏—Ç—å —Å–≤—è–∑—å —Ç—Ä–µ–∫-–∞—Ä—Ç–∏—Å—Ç
query = '''
SELECT *
FROM Track
JOIN Album
JOIN Artist
ON Track.AlbumId = Album.AlbumId
AND Album.ArtistId = Artist.ArtistId
'''
pd.read_sql(query, connect)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice,AlbumId,Title,ArtistId,ArtistId,Name
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99,1,For Those About To Rock We Salute You,1,1,AC/DC
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99,2,Balls to the Wall,2,2,Accept
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99,3,Restless and Wild,2,2,Accept
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99,3,Restless and Wild,2,2,Accept
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99,3,Restless and Wild,2,2,Accept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99,343,Respighi:Pines of Rome,226,226,Eugene Ormandy
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99,344,Schubert: The Late String Quartets & String Qu...,272,272,Emerson String Quartet
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99,345,Monteverdi: L'Orfeo,273,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99,346,Mozart: Chamber Music,274,274,Nash Ensemble
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,275,275,Philip Glass Ensemble

# –ì—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∞ –∏ —Ñ—É–Ω–∫—Ü–∏–∏ –∞–≥—Ä–µ–≥–∞—Ü–∏–∏

üìù **–ê–≥—Ä–µ–≥–∞—Ü–∏—è** - —Ñ—É–Ω–∫—Ü–∏—è, –∫–æ—Ç–æ—Ä–∞—è —Å—á–∏—Ç–∞–µ—Ç—Å—è –Ω–∞ –Ω–∞–±–æ—Ä–µ –∑–Ω–∞—á–µ–Ω–∏–π –∏ –æ–±—ä–µ–¥–∏–Ω—è–µ—Ç –∏—Ö –≤ –æ–¥–Ω–æ. –ù–∞–ø—Ä–∏–º–µ—Ä, –≤–∑—è—Ç–∏–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è –∏–ª–∏ –ø–æ–¥—Å—á–µ—Ç —á–∏—Å–ª–∞ —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –≤ –≥—Ä—É–ø–ø–µ

–ú—ã –º–æ–∂–µ–º –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∞—Ç—å —Å—Ç—Ä–æ–∫–∏ —Ç–∞–±–ª–∏—Ü—ã –Ω–∞ –æ—Å–Ω–æ–≤–µ –∫–∞–∫–æ–≥–æ-—Ç–æ –∑–Ω–∞—á–µ–Ω–∏—è –∏ —Å—á–∏—Ç–∞—Ç—å —Ñ—É–Ω–∫—Ü–∏–∏ –∞–≥—Ä–µ–≥–∞—Ü–∏–∏ –≤–Ω—É—Ç—Ä–∏ –≥—Ä—É–ø–ø—ã

üìù **COUNT** - —Ñ—É–Ω–∫—Ü–∏—è, –∫–æ—Ç–æ—Ä–∞—è —Å—á–∏—Ç–∞–µ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —ç–ª–µ–º–µ–Ω—Ç–æ–≤



```sql
SELECT COUNT(*)
FROM —Ç–∞–±–ª–∏—Ü–∞
```

```sql
SELECT COUNT(DISTINCT(–∫–æ–ª–æ–Ω–∫–∞))
FROM —Ç–∞–±–ª–∏—Ü–∞
```

In [ ]:
# ‚úèÔ∏è
# –û—Ç–≤–µ—Ç–∏–º –Ω–∞ –≤–æ–ø—Ä–æ—Å, —Å–∫–æ–ª—å–∫–æ –∞—Ä—Ç–∏—Å—Ç–æ–≤ –≤ —Ç–∞–±–ª–∏—Ü–µ
pd.read_sql('SELECT count(*) from Artist', connect)

   count(*)
0       275

–°—Ç—Ä–æ—á–∫–∏ —Å –æ–¥–∏–Ω–∞–∫–æ–≤—ã–º –∑–Ω–∞—á–µ–Ω–∏–µ–º –≤ –∫–æ–ª–æ–Ω–∫–µ –∞–≥—Ä–µ–≥–∞—Ü–∏–∏ –æ–±—ä–µ–¥–∏–Ω—è—é—Ç—Å—è –≤ –≥—Ä—É–ø–ø—É, –∏ –ø–æ –Ω–∏–º —Å–º–æ–∂–Ω–æ –ø–æ—Å—á–∏—Ç–∞—Ç—å —Ñ—É–Ω–∫—Ü–∏—é –∞–≥—Ä–µ–≥–∞—Ü–∏–∏:
```sql
SELECT –∫–æ–ª–æ–Ω–∫–∞ –∞–≥—Ä–µ–≥–∞—Ü–∏–∏, COUNT(–∫–æ–ª–æ–Ω–∫–∞1), AVG(–∫–æ–ª–æ–Ω–∫–∞2)
FROM —Ç–∞–±–ª–∏—Ü–∞

GROUP BY –∫–æ–ª–æ–Ω–∫–∞ –∞–≥—Ä–µ–≥–∞—Ü–∏–∏
```

In [ ]:
# ‚ñ∂Ô∏è‚ñ∂Ô∏è
# –ê —Ç–µ–ø–µ—Ä—å —Å–≥—Ä—É–ø–ø–∏—Ä—É–µ–º –¥–∞–Ω–Ω—ã–µ –∏–∑ —Ç–∞–±–ª–∏—Ü—ã –∞–ª—å–±–æ–º–æ–≤ –ø–æ –∞—Ä—Ç–∏—Å—Ç–∞–º –∏ –ø–æ—Å–º–æ—Ç—Ä–∏–º,
# —Å–∫–æ–ª—å–∫–æ –∞–ª—å–±–æ–º–æ–≤ —É –∫–∞–∂–¥–æ–≥–æ –∞—Ä—Ç–∏—Å—Ç–∞

query = '''
SELECT ArtistId, COUNT(title)
FROM Album

GROUP BY ArtistId
'''


pd.read_sql(query, connect)

     ArtistId  COUNT(title)
0           1             2
1           2             2
2           3             1
3           4             1
4           5             1
..        ...           ...
199       271             1
200       272             1
201       273             1
202       274             1
203       275             1

[204 rows x 2 columns]

In [ ]:
query = '''
SELECT ArtistId, COUNT(title)
FROM Album

GROUP BY ArtistId

ORDER BY COUNT(title)
'''


pd.read_sql(query, connect)

     ArtistId  COUNT(title)
0           3             1
1           4             1
2           5             1
3           7             1
4           9             1
..        ...           ...
199        50            10
200       150            10
201        58            11
202        22            14
203        90            21

[204 rows x 2 columns]

–ù–∏—á–µ–≥–æ –Ω–µ –ø–æ–Ω—è—Ç–Ω–æ, –¥–∞–≤–∞–π—Ç–µ –¥–æ–±–∞–≤–∏–º —Å—é–¥–∞ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ —Å–∞–º–æ–º –∞—Ä—Ç–∏—Å—Ç–µ

# –í–ª–æ–∂–µ–Ω–Ω—ã–µ –ø–æ–¥–∑–∞–ø—Ä–æ—Å—ã

–ú—ã –º–æ–∂–µ–º –¥–µ–ª–∞—Ç—å –≤–ª–æ–∂–µ–Ω–Ω—ã–µ –ø–æ–¥–∑–∞–ø—Ä–æ—Å—ã –∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –∏—Ö –∫–∞–∫ —Ç–∞–±–ª–∏—Ü—ã


```sql
SELECT ...
FROM (
    SELECT ... FROM ...
)
...
```

In [ ]:
# ‚ñ∂Ô∏è‚ñ∂Ô∏è
# –û–±—ä–µ–¥–∏–Ω–∏–º –∑–∞–ø—Ä–æ—Å GROUP BY –∏ JOIN

query = '''
SELECT name, COUNT(title)
FROM (
    SELECT *
    FROM Artist
    JOIN Album
    ON Artist.ArtistId = Album.ArtistId
)

GROUP BY name
'''

pd.read_sql(query, connect)

                                                  Name  COUNT(title)
0                                                AC/DC             2
1            Aaron Copland & London Symphony Orchestra             1
2                                       Aaron Goldberg             1
3    Academy of St. Martin in the Fields & Sir Nevi...             1
4    Academy of St. Martin in the Fields Chamber En...             1
..                                                 ...           ...
199                                 Vin√≠cius De Moraes             1
200                                     Wilhelm Kempff             1
201                                     Yehudi Menuhin             1
202                                           Yo-Yo Ma             1
203                                     Zeca Pagodinho             1

[204 rows x 2 columns]

In [ ]:
# ‚ñ∂Ô∏è‚ñ∂Ô∏è
# –û–±—ä–µ–¥–∏–Ω–∏–º –∑–∞–ø—Ä–æ—Å GROUP BY –∏ JOIN

query = '''
SELECT name, COUNT(title)
FROM (
    SELECT *
    FROM Artist
    JOIN Album
    ON Artist.ArtistId = Album.ArtistId
)

GROUP BY name
ORDER BY COUNT(title)
'''

pd.read_sql(query, connect)

                                                  Name  COUNT(title)
0            Aaron Copland & London Symphony Orchestra             1
1                                       Aaron Goldberg             1
2    Academy of St. Martin in the Fields & Sir Nevi...             1
3    Academy of St. Martin in the Fields Chamber En...             1
4    Academy of St. Martin in the Fields, John Birc...             1
..                                                 ...           ...
199                                          Metallica            10
200                                                 U2            10
201                                        Deep Purple            11
202                                       Led Zeppelin            14
203                                        Iron Maiden            21

[204 rows x 2 columns]

In [ ]:
# üë®üèª‚Äçüíª –í–æ–∑—å–º–∏—Ç–µ –∑–∞–ø—Ä–æ—Å –∏–∑ —É–ø—Ä–∞–∂–Ω–µ–Ω–∏—è "–û–±—ä–µ–¥–∏–Ω–∏—Ç–µ –≤—Å–µ 3 —Ç–∞–±–ª–∏—Ü—ã –≤ –æ–¥–Ω—É" –∏ –≤—ã–≤–µ–¥–∏—Ç–µ
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ç—Ä–µ–∫–æ–≤, –Ω–∞–ø–∏—Å–∞–Ω–Ω—ã—Ö –∫–∞–∂–¥—ã–º –∏—Å–ø–æ–ª–Ω–∏—Ç–µ–ª–µ–º

In [ ]:
# üë®üèª‚Äçüíª –û–±—ä–µ–¥–∏–Ω–∏—Ç–µ —Ç–∞–±–ª–∏—Ü—É Track –∏ —Ç–∞–±–ª–∏—Ü—É InvoiceLine.
# –°–∫–æ–ª—å–∫–æ —Ä–∞–∑ –±—ã–ª –∫—É–ø–ª–µ–Ω –∫–∞–∂–¥—ã–π —Ç—Ä–µ–∫?
# (–ü–æ–¥—Å—á–µ—Ç –º–æ–∂–Ω–æ –ø—Ä–æ–≤–µ—Å—Ç–∏ –ø–æ –∫–æ–ª–æ–Ω–∫–µ InvoiceID)

In [ ]:
# üë®üèª‚Äçüíª –û—Ç–≤–µ—Ç—å—Ç–µ –Ω–∞ –≤–æ–ø—Ä–æ—Å: –∫–∞–∫–æ–π –∞–≤—Ç–æ—Ä –Ω–∞–∏–±–æ–ª–µ–µ –∫–æ–º–º–µ—Ä—á–µ—Å–∫–∏ –ø–æ–ø—É–ª—è—Ä–µ–Ω?
# –ß—å–∏ —Ç—Ä–µ–∫–∏ –ø–æ–∫—É–ø–∞—é—Ç —á–∞—â–µ –≤—Å–µ–≥–æ?
# –î–ª—è —ç—Ç–æ–≥–æ –ø–æ–Ω–∞–¥–æ–±–∏—Ç—Å—è –æ–±—ä–µ–¥–∏–Ω–∏—Ç—å –∞–∂ 4 —Ç–∞–±–ª–∏—Ü—ã :)

# –ß—Ç–æ –º—ã —É–∑–Ω–∞–ª–∏ –Ω–∞ —ç—Ç–æ–º –∑–∞–Ω—è—Ç–∏–∏?
* –î–∞—Ç–∞-–∏–Ω–∂–µ–Ω–µ—Ä - —Å–ø–µ—Ü–∏–∞–ª–∏—Å—Ç –ø–æ —Å–±–æ—Ä—É –∏ —Ö—Ä–∞–Ω–µ–Ω–∏—é –¥–∞–Ω–Ω—ã—Ö, –≤ —ç—Ç–æ–π –ø—Ä–æ—Ñ–µ—Å—Å–∏–∏ –±–æ–ª—å—à–µ –≤—Å–µ–≥–æ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è –∏ –ø–æ—á—Ç–∏ –Ω–µ—Ç –º–∞—Ç–µ–º–∞—Ç–∏–∫–∏
* –û–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–π –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç - SQL
* –° –ø–æ–º–æ—â—å—é SQL –º–æ–∂–Ω–æ –ø–æ–ª—É—á–∞—Ç—å —Ä–∞–∑–ª–∏—á–Ω—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ –¥–∞–Ω–Ω—ã—Ö —Ç–∞–∫–∂–µ, –∫–∞–∫ –≤ Excel –∏–ª–∏ Pandas (DISTICT –∞–Ω–∞–ª–æ–≥ df[col].unique(), –æ–¥–∏–Ω–∞–∫–æ–≤—ã–π –º–µ—Ç–æ–¥ groupby).
* –†–∞–±–æ—Ç–∞—Ç—å —Å –±–∞–∑–∞–º–∏ –¥–∞–Ω–Ω—ã—Ö, –æ—Ç–ø—Ä–∞–≤–ª—è—è –≤ –Ω–∏—Ö SQL-–∑–∞–ø—Ä–æ—Å—ã –º–æ–∂–Ω–æ –≤–Ω—É—Ç—Ä–∏ –ø—Ä–æ–≥—Ä–∞–º–º—ã –Ω–∞ Python
* –ú—ã –ø–æ–∑–Ω–∞–∫–æ–º–∏–ª–∏—Å—å —Å –±–∞–∑–æ–≤—ã–µ –∫–æ–Ω—Å—Ç—Ä—É–∫—Ü–∏—è–º–∏ —è–∑—ã–∫–∞ SQL (SELECT, WHERE, JOIN), —É–∑–Ω–∞–ª–∏, –∫–∞–∫ —Ä–∏—Å—É—é—Ç—Å—è —Å—Ö–µ–º—ã –±–∞–∑ –¥–∞–Ω—ã—Ö –∏ –Ω–∞—É—á–∏–ª–∏—Å—å –∏–∑–≤–ª–µ–∫–∞—Ç—å –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –∏–∑ –¥–∞–Ω–Ω—ã—Ö –Ω–∞ –ø—Ä–∏–º–µ—Ä–µ –±–∞–∑—ã –¥–∞–Ω–Ω—ã—Ö –æ –ø—Ä–æ–¥–∞–∂–µ –º—É–∑—ã–∫–∞–ª—å–Ω—ã—Ö —Ç—Ä–µ–∫–∞—Ö